		.data
		str0:  .asciiz "Error1 "
		str1:  .asciiz "Error2 "
		str2:  .asciiz "Error3 "
		str3:  .asciiz "The number is so small!"
		str4:  .asciiz "Test do-while"
		str5:  .asciiz "#Result of do-while is "
		str6:  .asciiz "Test fibonacci"
		str7:  .asciiz "#Result of fibonacci is "
		str8:  .asciiz "Test relation operation"
		str9:  .asciiz "a1 should be 0:"
		str10:  .asciiz "a1 shouldn't be 0:"
		str11:  .asciiz "a1 should beq 32:"
		str12:  .asciiz "#Result of relation operation ends"
		str13:  .asciiz "Test (void function&switch int)"
		str14:  .asciiz "#Result of (void function&switch int) ends"
		str15:  .asciiz "Test expression"
		str16:  .asciiz "a should be 14:"
		str17:  .asciiz "#Result of expression ends"
		str18:  .asciiz "Test switch char"
		str19:  .asciiz ""
		str20:  .asciiz "#Result of switch char should be A-/"
		str21:  .asciiz "Test print char"
		str22:  .asciiz "1."
		str23:  .asciiz "2."
		str24:  .asciiz "3."
		str25:  .asciiz "4."
		str26:  .asciiz ""
		str27:  .asciiz "#Result of print char ends"
		str28:  .asciiz "Test multi-parameters"
		str29:  .asciiz "#Result of multi-parameters ends"
		str30:  .asciiz "Test single sentence"
		str31:  .asciiz "test0"
		str32:  .asciiz "#Result of single sentence ends"
